### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by WillZen**
I added some information to clarify the settings.

I hope I did everything in the right order. This is the first time I worked on GitHub.

### CODE REVIEW

**Comment by gsanchietti** [comment]
Can you split the UPS modification to another pull request so we can merge it?
If you have troubles doing it, I will do it for you during the merge process :)

Let me know!

**Comment by WillZen** [comment]
I will try it this evening and will write you about my success.

By the way  I am in Germany for the next three weeks. No time shift! :-D

Cheers

Am 27/07/2015 um 17:32 schrieb Giacomo:
>
> Can you split the UPS modification to another pull request so we can
> merge it?
> If you have troubles doing it, I will do it for you during the merge
> process :)
>
> Let me know!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NethServer/nethserver-docs/pull/79#issuecomment-125110611>.
>

-- 
Delta Gamma Consultant, PO BOX 1135, Hampton Nth VIC 3188
Tel. +61 449 756 225
Email: info@delta-gamma.com
Internet: www.delta-gamma.com
ABN 36 921 985 937

**Comment by WillZen** [comment]
I can't find anything to work with.
Did you already split and change it?

**Comment by gsanchietti** [comment]
Manually merged.

Note on admin user has not been merged.

**Pull request closed without merging**
